### ISSUE TITLE
Comment the Code

### ISSUE THREAD

**Issue by luni-moon** [theopcoder/PedestriaBotUpdated#5]
I have noticed in some files, that there are no comments that explain what the code below does. I don’t know if it is said within some examples I saw within the code, but it would be very helpful if you used the comment feature to help explain some details in further depth!

**Comment by theopcoder** [comment]
This repository is no longer being updated/supported. If you still want this issue fixed, please reanalyze the file in the new repository and if the issue still is persisting, please make a new issue or pull request. Thank you and have a great day!

Link to the official repository: https://github.com/theopcoder/PedestriaBotOfficial

**Comment by luni-moon** [comment]
Okay, thank you! May I close this issue then?

**Comment by luni-moon** [comment]
Well, I guess imma do it now then
